

from yacs.config import CfgNode as CN

POLICY = CN()
POLICY.TYPE = "DQN"
POLICY.MODEL = "RestrictedActionPolicy"
POLICY.DQN = CN()
POLICY.DQN.BUFFER_SIZE = int(70000)
POLICY.DQN.LEARNING_START = int(70000)
POLICY.DQN.BATCH_SIZE = 128
POLICY.DQN.TRAIN_FREQ = 12 # roughly each episode.
POLICY.DQN.EXPLORATION_FRACTION = 0.1
POLICY.DQN.EXPLORATION_INITIAL_EPS = 1.0
POLICY.DQN.EXPLORATION_FINAL_EPS = 0.075