

from yacs.config import CfgNode as CN
from .ppo import POLICY
from .meb import ME_BUFFER

POLICY = POLICY.clone()
POLICY.TYPE = "ModExpPPO"
POLICY.NORMALIZE_ADVANTAGE = False

POLICY.ME_C = CN()
POLICY.ME_C.TYPE = "ModExpCollector"
POLICY.ME_C.EP_SELECTOR = CN()
POLICY.ME_C.EP_SELECTOR.TYPE = "AllowUniqueEpisodes"
POLICY.ME_C.EP_SELECTOR.EXPRESSION_LIMIT = ME_BUFFER.EPISODE_BUDGET

POLICY.ME_C.EP_SELECTOR.INIT_REWARD_THRES = 0.0
POLICY.ME_C.EP_SELECTOR.MAX_REWARD_THRES = 0.80
POLICY.ME_C.EP_SELECTOR.REWARD_THRES_MULTIPLIER = 1.1
POLICY.ME_C.EP_SELECTOR.REWARD_MOVING_COEF = 0.9

POLICY.ME_C.EP_MODIFIER = CN()
POLICY.ME_C.EP_MODIFIER.TYPE = "HindsightModifier"
POLICY.ME_C.EP_MODIFIER.COLLECT_BASE = False


POLICY.ME_C.GAE_LAMBDA = 1.0
POLICY.ME_C.ME_BUFFER= ME_BUFFER

POLICY.ME_T = CN()
POLICY.ME_T.ENABLE = True
POLICY.ME_T.LOSS = CN()
POLICY.ME_T.RECOMPUTE_ADVANTAGES = False
POLICY.ME_T.LOSS.BC_COEF = 0.5
POLICY.ME_T.LOSS.POLICY_COEF = 1.0
POLICY.ME_T.LOSS.VALUE_COEF = 0.5
POLICY.ME_T.LOSS.ENTROPY_COEF = 5e-2
POLICY.ME_T.BATCH_SIZE = 512
POLICY.ME_T.MAX_EPOCH = 4
POLICY.ME_T.TRAIN_RATIO_THRES = 0.5
POLICY.ME_T.NORMALIZE_ADVANTAGE = False
### For PPO:
POLICY.ME_T.CLIP_RANGE = 0.2
POLICY.ME_T.CLIP_RANGE_VF = False
