
from yacs.config import CfgNode as CN

ME_BUFFER = CN()
ME_BUFFER.EPISODE_BUDGET = 2048 * 2
ME_BUFFER.MAX_EPISODE_LENGTH = 14
ME_BUFFER.APPROX_BATCH_SIZE = 512 * 16
ME_BUFFER.EPISODE_BATCH_SIZE = 3000
