

from yacs.config import CfgNode as CN


POLICY = CN()
POLICY.TYPE = "PPO"
POLICY.MODEL = "OldRestrictedActorCritic"
POLICY.PPO = CN()
POLICY.PPO.N_ENVS = 16
POLICY.PPO.N_STEPS = 2048
POLICY.PPO.BATCH_SIZE = 256
POLICY.PPO.PI_CONF = [512, 256, 128]
POLICY.PPO.VF_CONF = [512, 256, 128]
POLICY.PPO.N_EPOCHS = 1
POLICY.PPO.ENT_COEF = 0.1
POLICY.PPO.VF_COEF = 0.5
POLICY.PPO.GAE_LAMBDA = 0.5
POLICY.PPO.GAMMA = 1.0
POLICY.PPO.USE_SDE = False # Can only be used with a specific action space. 
POLICY.PPO.SDE_FREQ = -1
POLICY.NORMALIZE_ADVANTAGE = True
POLICY.PPO.ENABLE_TEMP = False
POLICY.PPO.INITIAL_TEMP = 0
# Basic
POLICY.ALLOW_COLLECT_MOD_EXP = False
POLICY.ALLOW_MOD_EXP_TRAIN = False
POLICY.VALUE_PRETRAIN = 0
POLICY.COLLECT_GRADIENTS = False
POLICY.GRADIENT_STEP_COUNT = 0