from yacs.config import CfgNode as CN

POLICY = CN()
POLICY.TYPE = "RWB"
POLICY.MODEL = "RestrictedActorCritic"
POLICY.RWB = CN()
POLICY.RWB.N_ENVS = 8
POLICY.RWB.N_STEPS = 32
POLICY.RWB.VF_COEF = 0.5
POLICY.RWB.ENT_COEF = 0.01
POLICY.RWB.GAMMA = 0.95
POLICY.RWB.NORMALIZE_ADVANTAGE = True
POLICY.RWB.RMS_PROP = False
POLICY.RWB.RMS_PROP_EPS = 1e-5
POLICY.RWB.SDE_FREQ = -1
POLICY.RWB.PI_CONF = [512, 256, 128]
POLICY.RWB.VF_CONF = [512, 256, 128]