from .baseline import BC
from yacs.config import CfgNode as CN

PLAD_BC = BC.clone()
PLAD_BC.TYPE = "PLADBC"
PLAD_BC.PLAD = CN()
PLAD_BC.PLAD.LATENT_EXECUTION = True
PLAD_BC.PLAD.INIT_LER = 0.5
PLAD_BC.PLAD.FINAL_LER = 0.5
PLAD_BC.PLAD.LE_ADD_NOISE = False
PLAD_BC.PLAD.LE_ONLY_ORIGINS = ["WS", "NR"]
PLAD_BC.PLAD.RL_MODE = False
PLAD_BC.PLAD.RL_REWARD_POW = 1
PLAD_BC.PLAD.RL_MOVING_BASELINE_ALPHA = 0.0
PLAD_BC.PLAD.EVAL_EPOCHS = 1

# Reward Weighting
PLAD_BC.PLAD.REWARD_WEIGHTING = False
PLAD_BC.PLAD.OPTIMIZER_RELOAD = False
PLAD_BC.PLAD.LOAD_BEST_BEFORE_SEARCH = True
PLAD_BC.PLAD.LOAD_BEST_TRAINING_WEIGHTS = False
PLAD_BC.PLAD.LOSS_BASED_POOR_EPOCH_RESET = False
PLAD_BC.PLAD.RESET_TRAIN_STATE = True

# BEST DATA STRUCT
PLAD_BC.PLAD.BPDS = CN()
PLAD_BC.PLAD.BPDS.TRAINING_DATA_SELECTION = "BEST"
PLAD_BC.PLAD.BPDS.BEST_PROG_COUNT = 1
PLAD_BC.PLAD.BPDS.STORE_SINGLE = True
# Options used only in prob mode:
PLAD_BC.PLAD.BPDS.GEN_SAMPLE_RATE = 0.33
PLAD_BC.PLAD.BPDS.N_SAMPLES_PER_ITEM = 10
PLAD_BC.PLAD.BPDS.DATA_SAMPLING_TEMPERATURE = 0.1
PLAD_BC.PLAD.BPDS.MULTIPLY_INPUT = False

# For the patience based setup
PLAD_BC.PLAD.SEARCH_PATIENCE = 5
PLAD_BC.PLAD.SEARCH_EVAL_THRESHOLD = 0.001
PLAD_BC.PLAD.MAX_SEARCH_WAIT = 10
PLAD_BC.PLAD.LENGTH_CURRICULUM = False
PLAD_BC.PLAD.INIT_LENGTH_ALPHA = 0
PLAD_BC.PLAD.FINAL_LENGTH_ALPHA = 0

# Beam search
PLAD_BC.BS = CN()
PLAD_BC.BS.ENABLE = True
PLAD_BC.BS.N_PROC = 2
PLAD_BC.BS.BEAM_SIZE = 10
PLAD_BC.BS.BATCH_SIZE = 48
PLAD_BC.BS.DETERMINISTIC = True
PLAD_BC.BS.RETURN_MULTIPLE = False # PLAD_BC.PLAD.BPDS.BEST_PROG_COUNT > 1
PLAD_BC.BS.BEAM_SELECTOR = 'rewards'
PLAD_BC.BS.STOCHASTIC_BS = False

PLAD_BC.WS = PLAD_BC.BS.clone()
PLAD_BC.WS.ENABLE = True
PLAD_BC.WS.MODEL = CN()
PLAD_BC.WS.SCORE_THRESHOLD = 0.01
PLAD_BC.WS.TRAINING_PATIENCE = 5
PLAD_BC.WS.N_EPOCHS = 10
PLAD_BC.WS.KLD_WEIGHT = 1.0
PLAD_BC.WS.ENT_WEIGHT = 0.00
PLAD_BC.WS.SAMPLE_COUNT = 9998
PLAD_BC.WS.SAMPLE_N_PROC = 2
PLAD_BC.WS.SAMPLE_BATCH_SIZE = 64
PLAD_BC.WS.INPUT_GATING = False

PLAD_BC.NR = CN()
PLAD_BC.NR.ENABLE = False
PLAD_BC.NR.SELECT_RANDOM = False
PLAD_BC.NR.N_PROC = 6
PLAD_BC.NR.N_AUGS = 50
PLAD_BC.NR.NOISE_RATE = 1.0
PLAD_BC.NR.POWER = 1.2
PLAD_BC.NR.INPUT_GATING = False
PLAD_BC.NR.NUMERIC_SIGMA = 0.05
PLAD_BC.NR.DISCRETE_DELTA = 1
PLAD_BC.NR.MAX_AUGS_PER_SAMPLE = 3


# DO 
PLAD_BC.DO = CN()
PLAD_BC.DO.ENABLE = False
PLAD_BC.DO.SELECT_RANDOM = False
PLAD_BC.DO.N_PROC = 1
PLAD_BC.DO.FREQUENCY = 8
PLAD_BC.DO.N_STEPS = 250
PLAD_BC.DO.LR = 0.01
PLAD_BC.DO.SAMPLE_COUNT = 5000
PLAD_BC.DO.EXHAUSTIVE = False
PLAD_BC.DO.INPUT_GATING = False

# Dead Code Removal:
PLAD_BC.GS = CN()
PLAD_BC.GS.ENABLE = False
PLAD_BC.GS.SELECT_RANDOM = False
PLAD_BC.GS.N_PROC = 1
PLAD_BC.GS.SAMPLE_COUNT = 5000 
PLAD_BC.GS.EXHAUSTIVE = True
PLAD_BC.GS.REWARD_THRESHOLD = 0.0 
PLAD_BC.GS.TD_MODE = "OLD"
PLAD_BC.GS.INPUT_GATING = False

# Code Splicing:
PLAD_BC.CS = CN()
PLAD_BC.CS.ENABLE = False
PLAD_BC.CS.SELECT_RANDOM = False
PLAD_BC.CS.EXHAUSTIVE = False
PLAD_BC.CS.N_PROC = 1
PLAD_BC.CS.SAMPLE_COUNT = 1500
PLAD_BC.CS.MAX_BOOL_COUNT = 11 
PLAD_BC.CS.NODE_MASKING_REQ = 0.9
PLAD_BC.CS.DUMMY_NODE = True
PLAD_BC.CS.RUN_GS = False
PLAD_BC.CS.RETURN_TOP_K = 1
PLAD_BC.CS.TOP_K = 15
PLAD_BC.CS.REWRITE_LIMIT = 10
PLAD_BC.CS.USE_CANONICAL = True
PLAD_BC.CS.USE_PROBS = False
PLAD_BC.CS.LOGPROB_THRESHOLD = 1
PLAD_BC.CS.REWARD_BASED_THRESH = False
PLAD_BC.CS.INPUT_GATING = False
PLAD_BC.CS.VALID_NODES = ["D", "B", "DUMMY", "RD"] 
PLAD_BC.CS.HIGHER_LANGUAGE = False
PLAD_BC.CS.FCSG_MODE = False

PLAD_BC.CS.CACHE_CONFIG = CN()
PLAD_BC.CS.CACHE_CONFIG.CACHE_SIZE = 25000
PLAD_BC.CS.CACHE_CONFIG.MAX_MASKING_RATE = 0.90
PLAD_BC.CS.CACHE_CONFIG.MERGE_NLIST = 300
PLAD_BC.CS.CACHE_CONFIG.MERGE_NPROBE = 25
PLAD_BC.CS.CACHE_CONFIG.MERGE_BIT_DISTANCE = 100
PLAD_BC.CS.CACHE_CONFIG.SEARCH_NLIST = 200
PLAD_BC.CS.CACHE_CONFIG.SEARCH_NPROBE = 10
PLAD_BC.CS.CACHE_CONFIG.N_PROGRAM_FOR_MERGE = 15000



# Merge Splice
PLAD_BC.CS.MERGE_SPLICE = CN()
PLAD_BC.CS.MERGE_SPLICE.ENABLE = False
PLAD_BC.CS.MERGE_SPLICE.INPUT_GATING = False
PLAD_BC.CS.MERGE_SPLICE.MIN_DELTA = 1
PLAD_BC.CS.MERGE_SPLICE.SAMPLE_COUNT = 5000

