
from yacs.config import CfgNode as CN

SIZE = 64

REWARD = CN()
REWARD.TYPE = "CHAMFER"
REWARD.POWER = 30
REWARD.FREQUENCY = "EPISODIC"
REWARD.CANVAS_SHAPE = [SIZE, SIZE]
REWARD.FALSE_PROGRAM_REWARD = - 0.5
REWARD.CDIST_NEG = 91.0
REWARD.USE_EXPLORATION_REWARD = False
REWARD.EXPLORATION_BETA = 0.0
REWARD.USE_CR_REWARD = False
REWARD.CR_REWARD_COEF = 0.0