
from yacs.config import CfgNode as CN
from .train_random import ENV
from .base_reward_3d import REWARD
ENV = ENV.clone()
ENV.TYPE = "CSG3DBase"
ENV.SET_LOADER_LIMIT = False
ENV.LOADER_LIMIT = 0
ENV.CSG_CONF = CN()
ENV.CSG_CONF.LANG_TYPE = "CSG3D"
ENV.CSG_CONF.RESOLUTION = 64
ENV.CSG_CONF.SCALE = 64
ENV.CSG_CONF.SCAD_RESOLUTION = 30
ENV.CSG_CONF.DRAW_TYPE = "basic"
ENV.CSG_CONF.DRAW_MODE = "direct"
ENV.CSG_CONF.BOOLEAN_COUNT = 5
ENV.CSG_CONF.PERM_MAX_LEN = 128
ENV.CSG_CONF.GENERATOR_N_PROCS = 1
ENV.CSG_CONF.VALID_DRAWS = ["sphere", "cylinder", "cuboid"]
ENV.CSG_CONF.VALID_TRANFORMS = ["scale", "rotate", "translate"]
ENV.CSG_CONF.VALID_BOOL = ['union', 'intersection', 'difference']
ENV.CSG_CONF.MAX_EXPRESSION_COMPLEXITY = 50
ENV.CSG_CONF.RESTRICT_DATASIZE = False
ENV.CSG_CONF.DATASIZE = 0

ENV.REWARD = REWARD.clone()
### For the PLAD data:
# PROPORTIONS = [202034, 197226, 191934, 188293, 184874, 180798, 177654, 173719, 171261, 167963, 164244]
# ENV.PROGRAM_PROPORTIONS = [1/2000000.0 for x in PROPORTIONS]
